# Simple search
# FIELD_LOOKUP = {
#     "NDC-Code": "ndc_with_dashes",
#     "Trade Name": "trade_name",
#     "Generic Name": "generic_name",
#     "Package Description": "package_description",
#     "Dosage Form": "dosage_form",
#     "Strength": "strength",
#     "Route": "route",
#     "Va Class": "va_class",
#     "Covered": "covered",
#     "Prime Vendor": "prime_vendor",
#     "Ingredient": "ingredient",
#     "Image Urls": "image_urls",
#     "Estimates Re-solication Date": "estimated_resolicitation_date",
#     "Offers": "offers",
#     "Estimated Annual Spend": "estimated_annual_spend",
#     "Notes": "notes",

#     "Vendor": "vendor__vendor_name",

#     "Contract Number": "contract__contract_number",
#     "Awardee": "contract__awardee",
#     "Awarded Value": "contract__awarded_value",
#     "Estimated Annual Quantities": "contract__estimated_annual_quantities",
#     "Contract Start Date": "contract__contract_start_date",
#     "Contract Stop Date": "contract__contract_stop_date",

#     "Manufactured By Name": "manufactured_by__name",
#     "Manufactured By Address": "manufactured_by__address",
#     "Manufactured For Name": "manufactured_for__name",
#     "Manufactured For Address": "manufactured_for__address",
#     "Distributed By Name": "distributed_by__name",
#     "Distributed By Address": "distributed_by__address",

#     "Price": "pricings__price",
#     "Price Start Date": "pricings__price_start_date",
#     "Price Stop Date": "pricings__price_stop_date",
#     "Price Type": "pricings__price_type",
#     "Non Taa Compliance": "pricings__non_taa_compliance"
# }

# COLUMN_FIELD_MAPPING = {
#     "NDC-Code": "ndc_with_dashes",
#     "Trade Name": "trade_name",
#     "Generic Name": "generic_name",
#     "Package Description": "package_description",
#     "Dosage Form": "dosage_form",
#     "Strength": "strength",
#     "Route": "route",
#     "Va Class": "va_class",
#     "Covered": "covered",
#     "Prime Vendor": "prime_vendor",
#     "Ingredient": "ingredient",
#     "Image Urls": "image_urls",
#     "Estimates Re-solication Date": "estimated_resolicitation_date",
#     "Offers": "offers",
#     "Estimated Annual Spend": "estimated_annual_spend",
#     "Notes": "notes",
#     "Vendor": "vendor",  
#     "Contract Number": "contract", 
#     "Awardee": None,  
#     "Awarded Value": None,  
#     "Estimated Annual Quantities": None,  
#     "Contract Start Date": None,  
#     "Contract Stop Date": None,  
#     "Manufactured By Name": "manufactured_by",  
#     "Manufactured By Address": None, 
#     "Manufactured For Name": "manufactured_for", 
#     "Manufactured For Address": None,  
#     "Distributed By Name": "distributed_by",  
#     "Distributed By Address": None,  
#     "Price": "price",  
#     "Price Start Date": "price_start_date", 
#     "Price Stop Date": "price_stop_date",  
#     "Price Type": "price_type",  
#     "Non Taa Compliance": "non_taa_compliance"
# }


# For ComSimple search
FIELD_LOOKUP = {
    "NDC-Code": "ndc_code",
    "Trade Name": "trade_name",
    "Generic Name": "generic_name",
    "Package Description": "package_description",
    "Dosage Form": "dosage_form",
    "Strength": "strength",
    "Route": "route",
    "Va Class": "va_class",
    "Covered": "covered",
    "Prime Vendor": "prime_vendor",
    "Ingredient": "ingredient",
    "Image Urls": "image_urls",
    "Estimates Re-solication Date": "estimated_resolicitation_date",
    "Offers": "offers",
    "Estimated Annual Spend": "estimated_annual_spend",
    "Notes": "notes",

    "Vendor": "vendor_name",

    "Contract Number": "contract_number",
    "Awardee": "contract_awardee",
    "Awarded Value": "contract_awarded_value",
    "Estimated Annual Quantities": "contract_estimated_annual_quantities",
    "Contract Start Date": "contract_start_date",
    "Contract Stop Date": "contract_stop_date",

    "Manufactured By Name": "manufactured_by_name",
    "Manufactured By Address": "manufactured_by_address",
    "Manufactured For Name": "manufactured_for_name",
    "Distributed By Name": "distributed_by_name",

    "Price": "pricings__price",
    "Price Start Date": "pricings__price_start_date",
    "Price Stop Date": "pricings__price_stop_date",
    "Price Type": "pricings__price_type",
    "Non Taa Compliance": "pricings__non_taa_compliance",
    
    "Min FSS Price": "min_fss_price",
    "Max FSS Price": "max_fss_price",
    "Min NC Price": "min_nc_price",
    "Max NC Price": "max_nc_price",
    "Min Big4 Price": "min_big4_price",
    "Max Big4 Price": "max_big4_price",
    
    "Source": "source",
}

COLUMN_FIELD_MAPPING = {
    "NDC-Code": "ndc_code",
    "Trade Name": "trade_name",
    "Generic Name": "generic_name",
    "Package Description": "package_description",
    "Dosage Form": "dosage_form",
    "Strength": "strength",
    "Route": "route",
    "Va Class": "va_class",
    "Covered": "covered",
    "Prime Vendor": "prime_vendor",
    "Ingredient": "ingredient",
    "Image Urls": "image_urls",
    "Estimates Re-solication Date": "estimated_resolicitation_date",
    "Offers": "offers",
    "Estimated Annual Spend": "estimated_annual_spend",
    "Notes": "notes",
    "Vendor": "vendor_name",  
    "Contract Number": "contract_number", 
    "Awardee": "contract_awardee",  
    "Awarded Value": "contract_awarded_value",  
    "Estimated Annual Quantities": "contract_estimated_annual_quantities",  
    "Contract Start Date": "contract_start_date",  
    "Contract Stop Date": "contract_stop_date",  
    "Manufactured By Name": "manufactured_by",  
    "Manufactured By Address": "manufactured_by_address", 
    "Manufactured For Name": "manufactured_for", 
    "Distributed By Name": "distributed_by",  
    "Price": "price",  
    "Price Start Date": "price_start_date", 
    "Price Stop Date": "price_stop_date",  
    "Price Type": "price_type",  
    "Non Taa Compliance": "non_taa_compliance", 
    "Min FSS Price": "min_fss_price",
    "Max FSS Price": "max_fss_price",
    "Min NC Price": "min_nc_price",
    "Max NC Price": "max_nc_price",
    "Min Big4 Price": "min_big4_price",
    "Max Big4 Price": "max_big4_price",
    "Source": "source", 
}



CONDITION_LOOKUP = {
    "Contains": "icontains",
    "Greater Than": "gt",
    "Less Than": "lt",
    "Equal": "exact",
    "Less Than Equal To": "lte",
    "Not Equal To": "exact",  # Handled with exclusion
    "Greater Than Equal To": "gte",
}
