# Generated by Django 5.0.4 on 2024-04-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('awardee', models.CharField(max_length=255)),
                ('awarded_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_annual_quantities', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_stop_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_with_dashes', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('va_class', models.CharField(max_length=50)),
                ('covered', models.BooleanField()),
                ('prime_vendor', models.BooleanField()),
                ('ingredient', models.CharField(max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='scraper.contract')),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_by', to='scraper.manufacturer')),
                ('manufactured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_by', to='scraper.manufacturer')),
                ('manufactured_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_for', to='scraper.manufacturer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='scraper.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PotentialLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ingredient', models.CharField(max_length=255)),
                ('applicant_holder', models.CharField(max_length=255)),
                ('te_code', models.CharField(blank=True, max_length=50, null=True)),
                ('market_status', models.CharField(max_length=50)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_leads', to='scraper.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_start_date', models.DateField()),
                ('price_stop_date', models.DateField()),
                ('price_type', models.CharField(max_length=50)),
                ('non_taa_compliance', models.CharField(max_length=50)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='scraper.drug')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='scraper.vendor'),
        ),
    ]
