# Generated by Django 5.0.4 on 2024-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_contract_awarded_value_alter_contract_awardee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='awardee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_annual_quantities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ingredient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='route',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='trade_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='va_class',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='active_ingredient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='applicant_holder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='market_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='te_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='non_taa_compliance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.TextField(),
        ),
    ]
