# Generated by Django 5.0.4 on 2024-05-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_drug_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentiallead',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='potentiallead',
            name='route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='potentiallead',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='te_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
