# Generated by Django 5.0.4 on 2024-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_potentiallead_dosage_form_potentiallead_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentiallead',
            name='te_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
