# Generated by Django 5.0.4 on 2024-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_potentiallead_te_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentiallead',
            name='drug',
        ),
    ]
