# Generated by Django 5.0.4 on 2024-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_alter_potentiallead_dosage_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentiallead',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='strength',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
