# Generated by Django 5.0.4 on 2024-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_alter_potentiallead_dosage_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentiallead',
            name='application_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
