# Generated by Django 5.0.4 on 2024-05-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_accessdrugshortagedata_asphdrugshortagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='asphdrugshortagedata',
            name='shortage_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NDCDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=100, unique=True, verbose_name='NDC Code')),
                ('description', models.TextField(verbose_name='Drug Description')),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndc_drugs_distributed_by', to='scraper.manufacturer')),
                ('manufactured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndc_drugs_manufactured_by', to='scraper.manufacturer')),
                ('manufactured_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndc_drugs_manufactured_for', to='scraper.manufacturer')),
            ],
        ),
    ]
