# Generated by Django 5.0.4 on 2024-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_ndcdrugdata_delete_ndcdrugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndcdrugdata',
            name='total_publishable_dollars_spent',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
