# Generated by Django 5.0.4 on 2024-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_alter_ndcdrugdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fioadrugsdata',
            name='mckesson_station_number',
            field=models.CharField(max_length=20),
        ),
    ]
