# Generated by Django 5.0.4 on 2024-05-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_rename_ndcdrugdata_fioapurchaserecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fioadrugsdata',
            name='ndc_code',
        ),
        migrations.CreateModel(
            name='FIOAUniqueNDCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('total_quantity_purchased', models.IntegerField(default=0)),
                ('total_publishable_dollars_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ingredient', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fioa_distributed_by', to='scraper.manufacturer')),
                ('manufactured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fioa_manufactured_by', to='scraper.manufacturer')),
                ('manufactured_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fioa_manufactured_for', to='scraper.manufacturer')),
            ],
            options={
                'verbose_name': 'FIOA Unique NDC Data',
                'verbose_name_plural': 'FIOA Unique NDC Data',
            },
        ),
        migrations.DeleteModel(
            name='FIOAPurchaseRecords',
        ),
    ]
