# Generated by Django 5.0.4 on 2024-05-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_remove_fioadrugsdata_ndc_code_fioauniquendcdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fioadrugsdata',
            name='ndc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='scraper.fioauniquendcdata'),
        ),
    ]
