# Generated by Django 5.0.4 on 2024-05-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_fioadrugsdata_ndc_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FIOADrugsData',
            new_name='FOIADrugsData',
        ),
        migrations.RenameModel(
            old_name='FIOAUniqueNDCData',
            new_name='FOIAUniqueNDCData',
        ),
    ]
