# Generated by Django 5.0.4 on 2024-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_rename_fioadrugsdata_foiadrugsdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DODDrugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
