# Generated by Django 5.0.4 on 2024-05-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_doddrugdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doddrugdata',
            old_name='code',
            new_name='ndc_code',
        ),
    ]
