# Generated by Django 5.0.4 on 2024-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_rename_code_doddrugdata_ndc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='awardee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='estimated_annual_quantities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ingredient',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='drug',
            name='package_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='route',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='strength',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='trade_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='drug',
            name='va_class',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='active_ingredient',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='applicant_holder',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='market_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='non_taa_compliance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=500),
        ),
    ]
