# Generated by Django 5.0.4 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0025_scrapingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsertionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_type', models.CharField(choices=[('FSS', 'FSS'), ('FOIA', 'FOIA'), ('DOD', 'DOD')], max_length=10)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contract',
            new_name='FSSContract',
        ),
        migrations.RenameModel(
            old_name='Drug',
            new_name='FSSDrug',
        ),
        migrations.RenameModel(
            old_name='Pricing',
            new_name='FSSPricing',
        ),
        migrations.RenameModel(
            old_name='Vendor',
            new_name='FSSVendor',
        ),
    ]
