# Generated by Django 5.0.4 on 2024-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0026_datainsertionrecord_rename_contract_fsscontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fssdrug',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
