# Generated by Django 5.0.4 on 2024-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0027_fssdrug_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiauniquendcdata',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foiauniquendcdata',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
