# Generated by Django 5.0.4 on 2024-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0030_rename_stationdata_foiastationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiastationdata',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foiastationdata',
            name='state',
            field=models.CharField(max_length=5),
        ),
    ]
