# Generated by Django 5.0.4 on 2024-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_alter_foiastationdata_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiastationdata',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
