# Generated by Django 5.0.4 on 2024-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0032_alter_foiastationdata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fssdrug',
            name='estimated_annual_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fssdrug',
            name='estimated_resolicitation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fssdrug',
            name='number_of_bidders',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
