# Generated by Django 5.1 on 2024-08-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0033_fssdrug_estimated_annual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fssdrug',
            name='offers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
