# Generated by Django 5.1 on 2024-08-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0035_fssdrug_estimated_annual_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fssdrug',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
