# Generated by Django 5.0.4 on 2024-08-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0036_fssdrug_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fssdrug',
            name='number_of_bidders',
        ),
    ]
