# Generated by Django 5.1 on 2024-08-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0038_manufacturer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fssdrug',
            name='estimated_annual_quantity',
        ),
    ]
