# Generated by Django 5.0.4 on 2024-08-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0039_remove_fssdrug_estimated_annual_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiauniquendcdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
