# Generated by Django 5.0.4 on 2024-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0040_foiauniquendcdata_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fssvendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
