# Generated by Django 5.0.4 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0041_fssvendor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentiallead',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='route',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='potentiallead',
            name='strength',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
