# Generated by Django 5.0.4 on 2024-08-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedDrugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=500, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('package_description', models.CharField(blank=True, max_length=500, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_quantity_purchased', models.IntegerField(blank=True, default=0, null=True)),
                ('total_publishable_dollars_spent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('manufactured_by', models.CharField(blank=True, max_length=500, null=True)),
                ('manufactured_for', models.CharField(blank=True, max_length=500, null=True)),
                ('distributed_by', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedDrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_start_date', models.DateField()),
                ('price_stop_date', models.DateField()),
                ('price_type', models.CharField(max_length=100)),
                ('non_taa_compliance', models.CharField(blank=True, max_length=255, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='smart_search.consolidateddrugdata')),
            ],
        ),
    ]
