# Generated by Django 5.0.4 on 2024-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidateddrugprice',
            name='price_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consolidateddrugprice',
            name='price_stop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consolidateddrugprice',
            name='price_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
