# Generated by Django 5.0.4 on 2024-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0004_consolidateddrugdata_contract_awarded_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='max_big4_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='max_fss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='max_nc_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='min_big4_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='min_fss_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consolidateddrugdata',
            name='min_nc_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
