# Generated by Django 5.0.4 on 2024-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0005_consolidateddrugdata_max_big4_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidateddrugdata',
            name='contract_awardee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consolidateddrugdata',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
