# Generated by Django 5.0.4 on 2024-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FOIAMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('strength', models.CharField(max_length=50)),
                ('total_dollar_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_units_purchased', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
