# Generated by Django 5.0.4 on 2024-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiamonthlystats',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foiamonthlystats',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
